config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  devise_for :users

  root to: "home#index"

  resources :links, only: [:index]
  resources :games, only: [:index]
  resources :videos, only: [:index, :show]
  get 'videos/category/:category_id' => 'videos#showCategory', as: 'video_categories'
  resources :newsletter_subscriptions, only: [ :create ]

  get '/admin' => 'admin#index', as: 'admin'

  get '/admin/users' => 'admin#user_index', as: 'admin_users'
  get '/admin/users/:id/edit' => 'admin#user_edit', as: 'admin_user_edit'
  patch '/admin/users/:id/update' => 'admin#user_update', as: 'admin_user_update'

  get '/admin/games' => 'admin#game_index', as: 'admin_games'
  get '/admin/games/new' => 'admin#game_new', as: 'admin_game_new'
  put '/admin/games/create' => 'admin#game_create', as: 'admin_game_create'
  get '/admin/games/:id/edit' => 'admin#game_edit', as: 'admin_game_edit'
  patch '/admin/games/:id/update' => 'admin#game_update', as: 'admin_game_update'

  get '/admin/videos' => 'admin#video_index', as: 'admin_videos'
  get '/admin/videos/new' => 'admin#video_new', as: 'admin_video_new'
  put '/admin/videos/create' => 'admin#video_create', as: 'admin_video_create'
  get '/admin/videos/:id/edit' => 'admin#video_edit', as: 'admin_video_edit'
  patch '/admin/videos/:id/update' => 'admin#video_update', as: 'admin_video_update'
end

app/views/admin/game_edit.html.haml
%h1
  = link_to 'Mon super panel admin', admin_path
  = link_to ' - games ', admin_games_path
  \- edit
= form_for @game, url: admin_game_update_path(@game), html: { class: 'form-horizontal auth' } do |f|
  - if @game.errors.size != 0
    %ul.alert.alert-danger
      - @game.errors.each do |error_key, error_value|
        %li= error_key.to_s + ' ' + error_value.to_s
  .form-group
    = f.label :name, 'Nom', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :name, autofocus: true
  .form-group
    = f.label :comment, 'Commentaire', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_area :comment, autofocus: true
  .form-group
    = f.label :link, 'Lien', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :link, autofocus: true
  .form-group
    = f.label :state, 'Etat', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.select :state, options_for_select([ ['En cours', Game::CURRENT], ['Fini', Game::FINISHED], ['Stoppé', Game::ABORTED] ], @game.state)
  .actions.text-center
    = f.submit I18n.t('devise.registrations.text.button'), class: "btn btn-primary"

app/views/admin/game_index.html.haml
%h1
  = link_to 'Mon super panel admin ', admin_path
  \- games
%table.table
  %thead
    %tr
      %td ID
      %td Nom
      %td Commentaire
      %td Lien
      %td Etat
      %td Editer
  %tbody.table-hover
    - @games.each do |game|
      %tr
        %td= game.id
        %td= game.name
        %td= game.comment
        %td= game.link
        %td= game.state
        %td
          = link_to admin_game_edit_path(game) do
            %i.fa.fa-pencil
.text-center
  = paginate @games

app/views/admin/index.html.haml
%h1 Mon super panel admin
%ul
  %li
    = link_to 'Gérer les utilisateurs', admin_users_path
  %li
    = link_to 'Gérer les jeux', admin_games_path
  %li
    = link_to 'Gérer les vidéos', admin_videos_path

app/views/admin/user_edit.html.haml
%h1
  = link_to 'Mon super panel admin', admin_path
  = link_to ' - users ', admin_users_path
  \- edit
= form_for @user, url: admin_user_update_path(@user), html: { class: 'form-horizontal auth' } do |f|
  - if @user.errors.size != 0
    %ul.alert.alert-danger
      - @user.errors.each do |error_key, error_value|
        %li= error_key.to_s + ' ' + error_value.to_s
  .form-group
    = f.label :username, I18n.t('devise.registrations.text.username'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :username, autofocus: true
  .form-group
    = f.label :email, I18n.t('devise.registrations.text.email'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.email_field :email, autofocus: true
  .form-group
    = f.label :description, I18n.t('devise.registrations.text.description'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_area :description, autofocus: true
  .form-group
    = f.label :favorite_game, I18n.t('devise.registrations.text.favorite_game'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :favorite_game, autofocus: true
  .form-group
    = f.label :favorite_type, I18n.t('devise.registrations.text.favorite_type'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :favorite_type, autofocus: true
  .form-group
    = f.label :role, I18n.t('devise.registrations.text.role'), class: 'col-sm-4 control-label'
    .col-sm-8
      = f.select :role, options_for_select([ ['Administrateur', User::ADMIN_TYPE], ['Utilisateur classique', User::CLASSIC_TYPE] ], @user.role)
  .actions.text-center
    = f.submit I18n.t('devise.registrations.text.button'), class: "btn btn-primary"

app/views/admin/user_index.html.haml
%h1
  = link_to 'Mon super panel admin ', admin_path
  \- users
%table.table
  %thead
    %tr
      %td ID
      %td Pseudo
      %td E-mail
      %td Description
      %td Date de naissance
      %td Jeux favoris
      %td Type de jeu favoris
      %td Editer
  %tbody.table-hover
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.username
        %td= user.email
        %td= user.description
        %td= user.birthday
        %td= user.favorite_game
        %td= user.favorite_type
        %td
          = link_to admin_user_edit_path(user) do
            %i.fa.fa-pencil
.text-center
  = paginate @users

app/views/admin/video_edit.html.haml
%h1
  = link_to 'Mon super panel admin', admin_path
  = link_to ' - videos ', admin_videos_path
  \- edit
= form_for @video, url: admin_video_update_path(@video), html: { class: 'form-horizontal auth' } do |f|
  - if @video.errors.size != 0
    %ul.alert.alert-danger
      - @video.errors.each do |error_key, error_value|
        %li= error_key.to_s + ' ' + error_value.to_s
  .form-group
    = f.label :name, 'Nom', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :name, autofocus: true
  .form-group
    = f.label :link, 'Lien', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :link, autofocus: true
  .form-group
    = f.label :video_category_id, 'Categorie', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.select :video_category_id, options_for_select(@video_categories, @video.video_category_id)
  .actions.text-center
    = f.submit I18n.t('devise.registrations.text.button'), class: "btn btn-primary"

app/views/admin/video_index.html.haml
%h1
  = link_to 'Mon super panel admin ', admin_path
  \- videos
%table.table
  %thead
    %tr
      %td ID
      %td Nom
      %td Lien
      %td Catégorie
      %td Editer
  %tbody.table-hover
    - @videos.each do |video|
      %tr
        %td= video.id
        %td= video.name
        %td= video.link
        %td
          - if video.video_category
            = video.video_category.name
          - else
            Aucune catégorie
        %td
          = link_to admin_video_edit_path(video) do
            %i.fa.fa-pencil
.text-center
  = paginate @videos