config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  devise_for :users

  root to: "home#index"

  resources :links, only: [:index]
  resources :games, only: [:index]
  resources :videos, only: [:index, :show]
  get 'videos/category/:category_id' => 'videos#showCategory', as: 'video_categories'
  resources :newsletter_subscriptions, only: [ :create ]

  get '/admin' => 'admin#index', as: 'admin'

  get '/admin/users' => 'admin#user_index', as: 'admin_users'
  get '/admin/users/:id/edit' => 'admin#user_edit', as: 'admin_user_edit'
  patch '/admin/users/:id/update' => 'admin#user_update', as: 'admin_user_update'

  get '/admin/games' => 'admin#game_index', as: 'admin_games'
  get '/admin/games/new' => 'admin#game_new', as: 'admin_game_new'
  put '/admin/games/create' => 'admin#game_create', as: 'admin_game_create'
  get '/admin/games/:id/edit' => 'admin#game_edit', as: 'admin_game_edit'
  patch '/admin/games/:id/update' => 'admin#game_update', as: 'admin_game_update'

  get '/admin/videos' => 'admin#video_index', as: 'admin_videos'
  get '/admin/videos/new' => 'admin#video_new', as: 'admin_video_new'
  put '/admin/videos/create' => 'admin#video_create', as: 'admin_video_create'
  get '/admin/videos/:id/edit' => 'admin#video_edit', as: 'admin_video_edit'
  patch '/admin/videos/:id/update' => 'admin#video_update', as: 'admin_video_update'
end

app/models/video.rb
class Video < ActiveRecord::Base
	paginates_per 50
	
	belongs_to :video_category
	belongs_to :image

	def image_link
		image = self.image
		image && image.filename ? ActionController::Base.helpers.asset_path(image.filename) : ActionController::Base.helpers.asset_path("placeholders/videogame-placeholder.png")
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @video_categories_concept   = VideoCategory.where(category_type: VideoCategory::TYPE_CONCEPT).eager_load(:videos)
    @video_categories_letsplay  = VideoCategory.where(category_type: VideoCategory::TYPE_LP).eager_load(:videos)
    @video_categories_other  = VideoCategory.where(category_type: VideoCategory::TYPE_OTHER).eager_load(:videos)
  end

  def show
    @video = Video.find_by_id(params[:id])

    if (!@video)
      respond_to do |format|
        format.html { redirect_to videos_url }
        format.json { render json: {}, :status => 404 }
      end
      return
    end

    respond_to do |format|
      format.html
      format.json { render json: @video.as_json }
    end
  end

  def showCategory
    @video_category = VideoCategory.where(id: params[:category_id]).eager_load(:videos).first

    if (!@video_category)
      respond_to do |format|
        format.html { redirect_to videos_url }
        format.json { render json: {}, :status => 404 }
      end
      return
    end
    respond_to do |format|
      format.html
      format.json { render json: @video_category.videos.limit(6).as_json({
        methods: :image_link,
        except: [:image_id],
      }) }
    end
  end
end

app/helpers/videos/show_helper.rb
module Videos
  module ShowHelper
    def self.view_parameters(video)
      {
        title: video.name,
        text: '',
        id: 'video_' + video.id.to_s,
        iframe: self.convertYTToEmbed(video.link)
      }
    end

    def self.convertYTToEmbed(youtube_url)
      if (youtube_url)
        youtube_url.gsub!('https://www.youtube.com/watch?v=', 'https://www.youtube.com/embed/')
      end
      youtube_url
    end
  end
end

app/views/videos/index.html.haml
%h1= I18n.t('title.concepts')
#categories-concept-container.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - @video_categories_concept.each do |category|
    .panel.panel-default
      .panel-heading{ role: "tab", id: 'heading-' + category.id.to_s }
        %h4.panel-title.clearfix
          %a.collapsed{"aria-controls" => "collapse" + category.id.to_s, "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse" + category.id.to_s, :role => "button"}
            = category.name
          = link_to video_categories_path(category), class: 'pull-right' do
            %i.fa.fa-eye
            %span= I18n.t('text.see-more')
      .panel-collapse.collapse{"aria-labelledby" => 'heading-' + category.id.to_s, :role => "tabpanel", id: "collapse" + category.id.to_s}
        .panel-body
  - if @video_categories_concept.size == 0
    %p= I18n.t('text.no-content')
%hr
%br
%h1= I18n.t('title.letsplay')
#categories-letsplay-container.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - @video_categories_letsplay.each do |category|
    .panel.panel-default
      .panel-heading{ role: "tab", id: 'heading-' + category.id.to_s }
        %h4.panel-title.clearfix
          %a.collapsed{"aria-controls" => "collapse" + category.id.to_s, "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse" + category.id.to_s, :role => "button"}
            = category.name
          = link_to video_categories_path(category), class: 'pull-right' do
            %i.fa.fa-eye
            %span= I18n.t('text.see-more')
      .panel-collapse.collapse{"aria-labelledby" => 'heading-' + category.id.to_s, :role => "tabpanel", id: "collapse" + category.id.to_s}
        .panel-body
  - if @video_categories_letsplay.size == 0
    %p= I18n.t('text.no-content')
%hr
%br
%h1= I18n.t('title.other')
#categories-other-container.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - @video_categories_other.each do |category|
    .panel.panel-default
      .panel-heading{ role: "tab", id: 'heading-' + category.id.to_s }
        %h4.panel-title.cleafix
          %a.collapsed{"aria-controls" => "collapse" + category.id.to_s, "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse" + category.id.to_s, :role => "button"}
            = category.name
          = link_to video_categories_path(category), class: 'pull-right' do
            %i.fa.fa-eye
            %span= I18n.t('text.see-more')
      .panel-collapse.collapse{"aria-labelledby" => 'heading-' + category.id.to_s, :role => "tabpanel", id: "collapse" + category.id.to_s}
        .panel-body
  - if @video_categories_other.size == 0
    %p= I18n.t('text.no-content')
#template.hidden
  #loader
    = render 'layouts/partials/loader'
  #gallery
    .col-sm-4.col-md-3
      .thumbnail.thumb-shadow.text-center
        =link_to video_url('video_id') do
          %img{ src: '#', id: 'thumb_img' }
          .caption
            %h3
  #empty-message
    %p= I18n.t('errors.videos.empty_category')
  #see-more-thumb
    .col-sm-4.col-md-3
      .thumbnail.thumb-shadow.text-center
        =link_to video_categories_url('category_id') do
          =image_tag 'placeholders/videogame-placeholder'
          .caption.see-more
            %h3
              = I18n.t('text.see-more')

app/views/videos/show.html.haml
=render 'layouts/partials/title_with_image', Videos::ShowHelper::view_parameters(@video)

app/views/videos/showCategory.html.haml
.row
  .text-center
    %h2= @video_category.name
  - @video_category.videos.each do |video|
    .col-sm-4.col-md-3
      =link_to video_path(video) do
        .thumbnail.thumb-shadow.text-center
          =image_tag video.image_link
          .caption.thumbnail-gray-caption
            %h3= video.name
  - if @video_category.videos.size == 0
    %hr
    %h3= I18n.t('text.no-content')