config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  devise_for :users

  root to: "home#index"

  resources :links, only: [:index]
  resources :games, only: [:index]
  resources :videos, only: [:index, :show]
  get 'videos/category/:category_id' => 'videos#showCategory', as: 'video_categories'
  resources :newsletter_subscriptions, only: [ :create ]

  get '/admin' => 'admin#index', as: 'admin'

  get '/admin/users' => 'admin#user_index', as: 'admin_users'
  get '/admin/users/:id/edit' => 'admin#user_edit', as: 'admin_user_edit'
  patch '/admin/users/:id/update' => 'admin#user_update', as: 'admin_user_update'

  get '/admin/games' => 'admin#game_index', as: 'admin_games'
  get '/admin/games/new' => 'admin#game_new', as: 'admin_game_new'
  put '/admin/games/create' => 'admin#game_create', as: 'admin_game_create'
  get '/admin/games/:id/edit' => 'admin#game_edit', as: 'admin_game_edit'
  patch '/admin/games/:id/update' => 'admin#game_update', as: 'admin_game_update'

  get '/admin/videos' => 'admin#video_index', as: 'admin_videos'
  get '/admin/videos/new' => 'admin#video_new', as: 'admin_video_new'
  put '/admin/videos/create' => 'admin#video_create', as: 'admin_video_create'
  get '/admin/videos/:id/edit' => 'admin#video_edit', as: 'admin_video_edit'
  patch '/admin/videos/:id/update' => 'admin#video_update', as: 'admin_video_update'
end

app/views/layouts/partials/_footer.html.haml
%section#footer.footer
  .container
    #newsletter.row
      .col-sm-6.col-sm-offset-3.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3
        %h2{"data-scroll-reveal" => "wait 0.45s, then enter left and move 80px over 1s"}= title
        %p{"data-scroll-reveal" => "wait 0.45s, then enter right and move 80px over 1s"}= description
        #newsletter_form
          = form_for(@newsletter_subscription, url: newsletter_subscriptions_path(@newsletter_subscription), html: { id: 'subscribe-form', class: 'subscribe-form' }) do |f|
            = f.email_field :email, class: 'subscribe-input', placeholder: placeholder
            = f.submit button_label, class: "subscribe-submit orange"
        #preview
    .row
      #share.col-sm-10.col-sm-offset-1.col-md-10.col-md-offset-1.col-lg-10.col-lg-offset-1
        #social_icons
          %ul
            %li
              =link_to("http://facebook.com/xplaylivex", "data-scroll-reveal": "wait 0.45s, then enter left and move 80px over 1s") do
                %i.fa.fa-facebook
            %li
              =link_to("http://twitter.com/xplaylivex", "data-scroll-reveal": "wait 0.45s, then enter left and move 80px over 1s") do
                %i.fa.fa-twitter
            %li
              =link_to("http://youtube.com/xplaylivex", "data-scroll-reveal": "wait 0.45s, then enter left and move 80px over 1s") do
                %i.fa.fa-youtube
            %li
              =link_to("http://twitch.tv/xplaylivex", "data-scroll-reveal": "wait 0.45s, then enter left and move 80px over 1s") do
                %i.fa.fa-twitch
        %p
          Copyright © 2016 xPlayLivex. Designed by
          %a{:href => "http://www.scriptcafe.in"} Script Cafe

app/views/layouts/partials/_header.html.haml
%body
  %header#home.header{:role => "banner"}
    .nav-container.clearfix
      .navbar-header
        %button.navbar-toggle{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %i.fa.fa-bars{ 'aria-hidden': "true"}
        =link_to root_path, class: "navbar-brand" do
          =image_tag logo
      %nav.collapse.navbar-collapse.bs-navbar-collapse.navbar-right{:role => "navigation"}
        %ul.nav.navbar-nav.menu
          -menu_header.each do |menu|
            %li
              =link_to menu[:link] do
                =menu[:text]
        %ul.nav.navbar-right.header-button
          - btn_header.each do |menu|
            %li
              =link_to menu[:link], class: menu[:active] ? 'active' : '', method: (menu[:method] ? menu[:method] : nil) do
                %button.btn.btn-primary{ type: "button" }= menu[:text]
    - flash.each do |name, msg|
      - if name == 'notice'
        .bg-notice.flash_messages.clearfix
          - if msg.is_a? String
            %button.pull-left.close{ type: "button", 'aria-label': "Close" }
              %span{ 'aria-hidden': "true"}
                &times;
            %p=msg
          - else
            %button.pull-left.close{ type: "button", 'aria-label': "Close" }
              %span{ 'aria-hidden': "true"}
                &times;
            - msg.each do |key, message_array|
              - message_array.each do |message|
                %p=message
      - elsif name == 'alert'
        .bg-alert.flash_messages.clearfix
          - if msg.is_a? String
            %button.pull-left.close{ type: "button", 'aria-label': "Close" }
              %span{ 'aria-hidden': "true"}
                &times;
            %p=msg
          - else
            %button.pull-left.close{ type: "button", 'aria-label': "Close" }
              %span{ 'aria-hidden': "true"}
                &times;
            - msg.each do |key, message_array|
              - message_array.each do |message|
                %p=message

app/views/layouts/partials/_loader.html.haml
.cssload-thecube
	.cssload-cube.cssload-c1
	.cssload-cube.cssload-c2
	.cssload-cube.cssload-c4
	.cssload-cube.cssload-c3

app/views/layouts/partials/_title.html.haml
%section#main.section.main
  .container
    .row
      .col-md-5
      .col-md-7
        .lp-element
          %h1{"data-scroll-reveal" => "wait 0.25s, then enter top and move 40px over 1s"}= title
          .blackdiv{"data-scroll-reveal" => "wait 0.35s, then enter left and move 40px over 1s"}
            %p.mainp= text
          %p{"data-scroll-reveal" => "wait 0.35s, then enter left and move 40px over 1s"}

app/views/layouts/partials/_title_with_image.html.haml
%section{:id => id }
  .container
    .row
      .col-md-12.sol-sm-12
        .text-center
          %h1{"data-scroll-reveal" => "wait 0.25s, then enter left and move 40px over 1s"}= title
          %p.lead{"data-scroll-reveal" => "wait 0.25s, then enter top and move 40px over 1s"}= text
      .gap
      .col-md-12.col-sm-12
        -if (defined?(image) && image)
          =image_tag image, "data-scroll-reveal": "wait 0.25s, then enter down and move 40px over 1s"
        - elsif (defined?(iframe) && iframe)
          .embed-responsive.embed-responsive-16by9
            %iframe.embed-responsive-item.center-block{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => iframe, :width => "560"}